-- AlterTable
ALTER TABLE "CostChange" ADD COLUMN     "volume" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "mile" SET DEFAULT 0,
ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "description" SET DEFAULT '',
ALTER COLUMN "nextMile" SET DEFAULT 0,
ALTER COLUMN "typeId" DROP NOT NULL;
